In [1]:
import sys

sys.path.append('../GraphStructureLearning')

In [2]:
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader
from dataset.make_traffic_dataset import METRLADatasetLoader
import numpy as np
from torch_geometric.data import Data, Batch

In [3]:
from utils.utils import build_batch_edge_index

In [4]:
dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

Extracting \tmp\ENZYMES\ENZYMES\ENZYMES.zip
Processing...
Done!


In [5]:
a = next(iter(loader))

In [6]:
a

DataBatch(edge_index=[2, 4284], x=[1095, 21], y=[32], batch=[1095], ptr=[33])

In [7]:
a.x

tensor([[ 3.0000,  5.7044, 11.9100,  ...,  1.0000,  0.0000,  0.0000],
        [11.0000, 15.1492, 41.9200,  ...,  1.0000,  0.0000,  0.0000],
        [ 7.0000, 10.0141, 30.8500,  ...,  1.0000,  0.0000,  0.0000],
        ...,
        [ 7.0000, 19.2769, 19.9300,  ...,  0.0000,  1.0000,  0.0000],
        [ 6.0000, 16.2709, 14.9500,  ...,  0.0000,  1.0000,  0.0000],
        [ 4.0000,  9.9870, 10.5500,  ...,  0.0000,  1.0000,  0.0000]])

In [8]:
a.y

tensor([0, 3, 2, 3, 2, 2, 0, 3, 4, 5, 5, 5, 2, 5, 4, 5, 0, 2, 3, 5, 3, 4, 2, 1,
        0, 2, 1, 2, 3, 2, 3, 1])

In [9]:
a.batch

tensor([ 0,  0,  0,  ..., 31, 31, 31])

In [11]:
a.edge_index

tensor([[   0,    0,    0,  ..., 1094, 1094, 1094],
        [   1,    2,    5,  ..., 1087, 1089, 1092]])

In [12]:
metr = METRLADatasetLoader(raw_data_dir='./data/METR-LA')
data_list = metr.get_dataset(12, 3)

loader = DataLoader(data_list, batch_size=2)
data = next(iter(loader))

In [13]:
data

DataBatch(x=[414, 2, 12], edge_index=[2], y=[414, 3], batch=[414], ptr=[3])

In [14]:
feature = metr.features
target = metr.targets
edge_index = metr.edges

In [15]:
batch_size = 2

In [16]:
data_batch = len(feature) // batch_size

In [17]:
f = []
t = []

for ii in range(data_batch):
    f.append(np.array(feature[ii:ii+batch_size]))
    t.append(np.array(target[ii:ii+batch_size]))
    
    batch = []
    for node in range(207):
        batch += [node]*batch_size
    batch = np.array(batch)
    
    

In [18]:
len(f)

17129

In [19]:
f[0][0].shape

(207, 2, 12)

In [20]:
feature[0].shape

(207, 2, 12)

In [21]:
np.stack((f[0][0], f[0][1]),axis=0).shape

(2, 207, 2, 12)

In [22]:
temp = np.concatenate((f[0][0], f[0][1]),axis=0)

In [23]:
temp.shape

(414, 2, 12)

In [24]:
temp[-1]

array([[ 0.45895067,  0.415655  , -2.6521542 , -2.6521542 ,  0.18474454,
         0.3785444 ,  0.28576788,  0.4032848 ,  0.4280252 ,  0.3166934 ,
         0.28841856,  0.48987615],
       [-1.7171322 , -1.7050823 , -1.6930324 , -1.6809825 , -1.6689326 ,
        -1.6568825 , -1.6448327 , -1.6327827 , -1.6207328 , -1.6086829 ,
        -1.596633  , -1.584583  ]], dtype=float32)

In [25]:
data.x[-1]

tensor([[ 0.4590,  0.4157, -2.6522, -2.6522,  0.1847,  0.3785,  0.2858,  0.4033,
          0.4280,  0.3167,  0.2884,  0.4899],
        [-1.7171, -1.7051, -1.6930, -1.6810, -1.6689, -1.6569, -1.6448, -1.6328,
         -1.6207, -1.6087, -1.5966, -1.5846]])