In [1]:
import sys

sys.path.append('../GraphStructureLearning')

In [2]:
import torch
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader
from dataset.make_traffic_dataset import TrafficDatasetLoader
import numpy as np
from torch_geometric.data import Data, Batch

from torch_geometric_temporal.signal import StaticGraphTemporalSignalBatch, temporal_signal_split

In [3]:
from utils.utils import build_batch_edge_index

In [10]:
metr = TrafficDatasetLoader(raw_data_dir='./data/PEMS-BAY', dataset_name='PEMS-BAY')
data_list, X = metr.get_dataset(12, 3, 1)

In [11]:
for batch in data_list:
    pass

In [12]:
batch

DataBatch(x=[325, 2, 12], edge_index=[2, 2694], y=[325, 3], batch=[325])

In [13]:
batch.x

tensor([[[0.9928, 0.9390, 1.0789,  ..., 1.0251, 0.9821, 1.0251],
         [1.5747, 1.5869, 1.5990,  ..., 1.6842, 1.6964, 1.7085]],

        [[0.4871, 0.4655, 0.4548,  ..., 0.4871, 0.4871, 0.5193],
         [1.5747, 1.5869, 1.5990,  ..., 1.6842, 1.6964, 1.7085]],

        [[0.4117, 0.2611, 0.5193,  ..., 0.6915, 0.7130, 0.7453],
         [1.5747, 1.5869, 1.5990,  ..., 1.6842, 1.6964, 1.7085]],

        ...,

        [[0.8422, 0.8314, 0.8099,  ..., 0.6915, 0.6915, 0.7346],
         [1.5747, 1.5869, 1.5990,  ..., 1.6842, 1.6964, 1.7085]],

        [[1.0574, 1.0574, 1.0574,  ..., 1.0574, 1.0574, 1.0574],
         [1.5747, 1.5869, 1.5990,  ..., 1.6842, 1.6964, 1.7085]],

        [[0.9713, 0.7991, 0.6808,  ..., 0.4225, 0.4763, 0.7130],
         [1.5747, 1.5869, 1.5990,  ..., 1.6842, 1.6964, 1.7085]]])

In [14]:
batch.edge_index

tensor([[  0,   1,   2,  ..., 324, 324, 324],
        [  0,   1,   2,  ..., 257, 310, 324]])

In [15]:
batch.y

tensor([[ 1.0359,  1.1219,  1.0466],
        [ 0.5516,  0.5086,  0.4763],
        [ 0.6808,  0.6700,  0.7130],
        [-0.0725, -0.0725, -0.0295],
        [ 0.0243,  0.0781,  0.1104],
        [ 0.5301,  0.4333,  0.4655],
        [ 0.4333,  0.5731,  0.6377],
        [ 0.6915,  0.7023,  0.7130],
        [ 0.2611,  0.2396,  0.3364],
        [ 0.7884,  0.5947,  0.6700],
        [ 0.6269,  0.6485,  0.5731],
        [ 0.5731,  0.5731,  0.6700],
        [ 0.5947,  0.6269,  0.5731],
        [ 0.9498,  0.8744,  0.8960],
        [ 0.5731,  0.7023,  0.5839],
        [ 0.7023,  0.6592,  0.6915],
        [ 0.5731,  0.6054,  0.5086],
        [ 0.7023,  0.6485,  0.4655],
        [ 0.6915,  0.6915,  0.7130],
        [ 0.5839,  0.6054,  0.6485],
        [ 0.6592,  0.5947,  0.6054],
        [ 0.4978,  0.4655,  0.6485],
        [ 0.6377,  0.6808,  0.7130],
        [ 0.4333,  0.4978,  0.3256],
        [ 0.7561,  0.8422,  0.7561],
        [ 0.7346,  0.7346,  0.7884],
        [ 0.8099,  0.7776,  0.7453],
 

In [16]:
X.shape

torch.Size([325, 2, 52105])

In [18]:
X[:,0,:]

tensor([[0.9821, 0.9928, 1.0251,  ..., 1.0359, 1.1219, 1.0466],
        [0.6054, 0.5839, 0.6592,  ..., 0.5516, 0.5086, 0.4763],
        [0.9390, 0.9175, 0.8960,  ..., 0.6808, 0.6700, 0.7130],
        ...,
        [0.7023, 0.7023, 0.7023,  ..., 0.7130, 0.7453, 0.7453],
        [1.0143, 1.0036, 1.0143,  ..., 1.0574, 1.0574, 1.0574],
        [0.6485, 0.6592, 0.6377,  ..., 0.5193, 0.7130, 0.6700]])

In [19]:
X[:,1,:]

tensor([[-1.6127, -1.6005, -1.5883,  ...,  1.7207,  1.7328,  1.7450],
        [-1.6127, -1.6005, -1.5883,  ...,  1.7207,  1.7328,  1.7450],
        [-1.6127, -1.6005, -1.5883,  ...,  1.7207,  1.7328,  1.7450],
        ...,
        [-1.6127, -1.6005, -1.5883,  ...,  1.7207,  1.7328,  1.7450],
        [-1.6127, -1.6005, -1.5883,  ...,  1.7207,  1.7328,  1.7450],
        [-1.6127, -1.6005, -1.5883,  ...,  1.7207,  1.7328,  1.7450]])