In [1]:
import sys

sys.path.append('../GraphStructureLearning')

In [2]:
from glob import glob
import yaml
from easydict import EasyDict as edict

In [3]:
import pickle
import os
from os import path
import torch
import numpy as np

from torch_geometric.data import Data

In [10]:
from torch_geometric.utils import dense_to_sparse


In [4]:
config_file = glob('./config/GTS/*.yaml')[0]
config = edict(yaml.load(open(config_file, 'r'), Loader=yaml.FullLoader))

In [8]:
A = np.array([[1,1,0], [1,0,1], [0,1,0]])

In [30]:
A = np.array([[5,2,0], [3,0,2], [0,2,0]])

In [16]:
A_2 = np.matmul(A,A)
A_2

array([[2, 1, 1],
       [1, 2, 0],
       [1, 0, 1]])

In [17]:
D = np.array([[2,0,0], [0,2,0], [0,0,1]])

In [20]:
D_ = np.linalg.inv(D)

In [31]:
D_

array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 1. ]])

In [32]:
t = np.matmul(D_, A)

In [33]:
t

array([[2.5, 1. , 0. ],
       [1.5, 0. , 1. ],
       [0. , 2. , 0. ]])

In [34]:
t_2 = np.matmul(t,t)

In [35]:
t_2

array([[7.75, 2.5 , 1.  ],
       [3.75, 3.5 , 0.  ],
       [3.  , 0.  , 2.  ]])

In [36]:
t_3 = np.matmul(t_2, t)

In [37]:
t_3

array([[23.125,  9.75 ,  2.5  ],
       [14.625,  3.75 ,  3.5  ],
       [ 7.5  ,  7.   ,  0.   ]])

In [15]:
a = torch.Tensor(100,100) + 1

In [16]:
outputs, attr = dense_to_sparse(a)

In [17]:
outputs

tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [ 0,  1,  2,  ..., 97, 98, 99]])

In [18]:
attr.shape

torch.Size([10000])

In [19]:
outputs.shape

torch.Size([2, 10000])